/**
 * Loads data/parity/scoring_scenarios.json (generated by
 * worker/generate_parity_fixtures.py, Python as the reference
 * implementation) and checks recomputeRoute reproduces the same numbers.
 * worker/tests/test_scoring_parity.py loads the exact same file -- if either
 * implementation drifts from docs/scoring.md, one of these two suites
 * catches it.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { recomputeRoute } from "./scoring";
import type { LegInputs } from "./scoring";

const __dirnameLocal = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirnameLocal, "..", "..");
const FIXTURES_PATH = path.join(REPO_ROOT, "data", "parity", "scoring_scenarios.json");

interface RawLeg {
  venue_slug: string;
  maker_bps: number | null;
  taker_bps: number | null;
  spread_bps: number | null;
  impact_bps_10k: number | null;
  impact_bps_50k: number | null;
  impact_bps_100k: number | null;
  depth_usd_10k: number | null;
  depth_usd_50k: number | null;
  depth_usd_100k: number | null;
  funding_rate_annualized_7d_mean: number | null;
  points_per_usd_volume_estimate: number | null;
  pair_weight_multiplier: number;
  maker_counts_for_points: boolean | null;
  taker_counts_for_points: boolean | null;
  maker_boost_multiplier: number;
}

interface Scenario {
  name: string;
  long_leg: RawLeg;
  short_leg: RawLeg;
  params: { notional_usd: number; hold_hours: number };
  expected: {
    cost_per_point_usd: number;
    points_per_1m_volume: number;
    weekly_cost_usd: number;
    funding_cost_usd: number;
    total_points: number;
    long_order_type: "maker" | "taker";
    short_order_type: "maker" | "taker";
    risks: { fill_risk: boolean; beyond_measured_depth: boolean };
  };
}

function toLegInputs(raw: RawLeg): LegInputs {
  return {
    venue: raw.venue_slug,
    makerBps: raw.maker_bps,
    takerBps: raw.taker_bps,
    spreadBps: raw.spread_bps,
    impactBps10k: raw.impact_bps_10k,
    impactBps50k: raw.impact_bps_50k,
    impactBps100k: raw.impact_bps_100k,
    depthUsd10k: raw.depth_usd_10k,
    depthUsd50k: raw.depth_usd_50k,
    depthUsd100k: raw.depth_usd_100k,
    fundingRateAnnualized7dMean: raw.funding_rate_annualized_7d_mean,
    pointsPerUsdVolumeEstimate: raw.points_per_usd_volume_estimate,
    pairWeightMultiplier: raw.pair_weight_multiplier,
    makerCountsForPoints: raw.maker_counts_for_points,
    takerCountsForPoints: raw.taker_counts_for_points,
    makerBoostMultiplier: raw.maker_boost_multiplier,
  };
}

const scenarios: Scenario[] = JSON.parse(fs.readFileSync(FIXTURES_PATH, "utf-8"));

describe("scoring parity with the Python reference engine", () => {
  it.each(scenarios.map((s) => [s.name, s] as const))("%s", (_name, scenario) => {
    const longLeg = toLegInputs(scenario.long_leg);
    const shortLeg = toLegInputs(scenario.short_leg);
    const result = recomputeRoute(longLeg, shortLeg, {
      notionalUsd: scenario.params.notional_usd,
      holdHours: scenario.params.hold_hours,
    });

    expect(result.costPerPointUsd).toBeCloseTo(scenario.expected.cost_per_point_usd, 9);
    expect(result.pointsPer1mVolume).toBeCloseTo(scenario.expected.points_per_1m_volume, 6);
    expect(result.weeklyCostUsd).toBeCloseTo(scenario.expected.weekly_cost_usd, 6);
    expect(result.fundingCostUsd).toBeCloseTo(scenario.expected.funding_cost_usd, 6);
    expect(result.totalPoints).toBeCloseTo(scenario.expected.total_points, 6);
    expect(result.long.orderType).toBe(scenario.expected.long_order_type);
    expect(result.short.orderType).toBe(scenario.expected.short_order_type);
    expect(result.risks.fillRisk).toBe(scenario.expected.risks.fill_risk);
    expect(result.risks.beyondMeasuredDepth).toBe(scenario.expected.risks.beyond_measured_depth);
  });
});
