"""Loads data/parity/scoring_scenarios.json (generated by
worker/generate_parity_fixtures.py, Python as the reference implementation)
and re-derives each `expected` block via score_route. web/lib/scoring.parity.test.ts
loads the exact same file and must reproduce the same numbers -- if either
implementation drifts from docs/scoring.md, one of these two suites catches it.
"""

import json
from pathlib import Path

import pytest

from perpfarm.scoring.engine import score_route
from perpfarm.scoring.types import LegInputs, ScoringParams

FIXTURES_PATH = Path(__file__).resolve().parents[2] / "data" / "parity" / "scoring_scenarios.json"
SCENARIOS = json.loads(FIXTURES_PATH.read_text(encoding="utf-8"))


@pytest.mark.parametrize("scenario", SCENARIOS, ids=[s["name"] for s in SCENARIOS])
def test_scenario_matches_expected(scenario):
    long_leg = LegInputs(**scenario["long_leg"])
    short_leg = LegInputs(**scenario["short_leg"])
    params = ScoringParams(**scenario["params"])
    expected = scenario["expected"]

    result = score_route(long_leg, short_leg, params)

    assert result.is_complete
    assert result.cost_per_point_usd == pytest.approx(expected["cost_per_point_usd"])
    assert result.points_per_1m_volume == pytest.approx(expected["points_per_1m_volume"])
    assert result.weekly_cost_usd == pytest.approx(expected["weekly_cost_usd"])
    assert result.cost_breakdown["funding_cost_usd"] == pytest.approx(expected["funding_cost_usd"])
    assert result.cost_breakdown["total_points"] == pytest.approx(expected["total_points"])
    assert result.recommended_execution["long"]["order_type"] == expected["long_order_type"]
    assert result.recommended_execution["short"]["order_type"] == expected["short_order_type"]
    assert result.risks == expected["risks"]
